### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by thomased** [wviechtb/metadat#1]
### todo

- [X] create todo
- [X] naming scheme
  - dat.authoryear
  - dat.authoryearb.1
  - dat.authoryear.corr
  - dat.authoryear.phylo
- [X] boilerplate function for doc generation
- [ ] port over existing datasets
- [X] document/describe the workflow (raw -> clean data) and add contributor guidelines
- [ ] travis
- [ ] tests

**Comment by nealhaddaway** [comment]
I'd LOVE to see a manuscript on metadat when you have time, team! Here's a link to the special series website: https://estechseries.github.io/
